require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Icd10dxesController do

  # This should return the minimal set of attributes required to create a valid
  # Icd10dx. As you add validations to Icd10dx, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Icd10dxesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all icd10dxes as @icd10dxes" do
      icd10dx = Icd10dx.create! valid_attributes
      get :index, {}, valid_session
      assigns(:icd10dxes).should eq([icd10dx])
    end
  end

  describe "GET show" do
    it "assigns the requested icd10dx as @icd10dx" do
      icd10dx = Icd10dx.create! valid_attributes
      get :show, {:id => icd10dx.to_param}, valid_session
      assigns(:icd10dx).should eq(icd10dx)
    end
  end

  describe "GET new" do
    it "assigns a new icd10dx as @icd10dx" do
      get :new, {}, valid_session
      assigns(:icd10dx).should be_a_new(Icd10dx)
    end
  end

  describe "GET edit" do
    it "assigns the requested icd10dx as @icd10dx" do
      icd10dx = Icd10dx.create! valid_attributes
      get :edit, {:id => icd10dx.to_param}, valid_session
      assigns(:icd10dx).should eq(icd10dx)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Icd10dx" do
        expect {
          post :create, {:icd10dx => valid_attributes}, valid_session
        }.to change(Icd10dx, :count).by(1)
      end

      it "assigns a newly created icd10dx as @icd10dx" do
        post :create, {:icd10dx => valid_attributes}, valid_session
        assigns(:icd10dx).should be_a(Icd10dx)
        assigns(:icd10dx).should be_persisted
      end

      it "redirects to the created icd10dx" do
        post :create, {:icd10dx => valid_attributes}, valid_session
        response.should redirect_to(Icd10dx.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved icd10dx as @icd10dx" do
        # Trigger the behavior that occurs when invalid params are submitted
        Icd10dx.any_instance.stub(:save).and_return(false)
        post :create, {:icd10dx => { "code" => "invalid value" }}, valid_session
        assigns(:icd10dx).should be_a_new(Icd10dx)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Icd10dx.any_instance.stub(:save).and_return(false)
        post :create, {:icd10dx => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested icd10dx" do
        icd10dx = Icd10dx.create! valid_attributes
        # Assuming there are no other icd10dxes in the database, this
        # specifies that the Icd10dx created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Icd10dx.any_instance.should_receive(:update).with({ "code" => "MyString" })
        put :update, {:id => icd10dx.to_param, :icd10dx => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested icd10dx as @icd10dx" do
        icd10dx = Icd10dx.create! valid_attributes
        put :update, {:id => icd10dx.to_param, :icd10dx => valid_attributes}, valid_session
        assigns(:icd10dx).should eq(icd10dx)
      end

      it "redirects to the icd10dx" do
        icd10dx = Icd10dx.create! valid_attributes
        put :update, {:id => icd10dx.to_param, :icd10dx => valid_attributes}, valid_session
        response.should redirect_to(icd10dx)
      end
    end

    describe "with invalid params" do
      it "assigns the icd10dx as @icd10dx" do
        icd10dx = Icd10dx.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Icd10dx.any_instance.stub(:save).and_return(false)
        put :update, {:id => icd10dx.to_param, :icd10dx => { "code" => "invalid value" }}, valid_session
        assigns(:icd10dx).should eq(icd10dx)
      end

      it "re-renders the 'edit' template" do
        icd10dx = Icd10dx.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Icd10dx.any_instance.stub(:save).and_return(false)
        put :update, {:id => icd10dx.to_param, :icd10dx => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested icd10dx" do
      icd10dx = Icd10dx.create! valid_attributes
      expect {
        delete :destroy, {:id => icd10dx.to_param}, valid_session
      }.to change(Icd10dx, :count).by(-1)
    end

    it "redirects to the icd10dxes list" do
      icd10dx = Icd10dx.create! valid_attributes
      delete :destroy, {:id => icd10dx.to_param}, valid_session
      response.should redirect_to(icd10dxes_url)
    end
  end

end
